### PR TITLE
Bump version for release

### PR DESCRIPTION
**Pull request by zware**
For #37.

### CODE REVIEW

**Comment by Mariatta** [comment]
Do we have changelog to update?

**Comment by Mariatta** [comment]
and thanks for creating the PR so quickly! I was about to do it

**Comment by zware** [comment]
Doesn't appear that we do.

**Comment by Mariatta** [comment]
Does anyone else have opinion on whether we should start adding changelog beginning at this release?

**Comment by zware** [comment]
I think this project is low-traffic enough that interested parties can just read through the commit log.  This would only be the 21st commit in ~3 years, after all :)

**Comment by Mariatta** [comment]
ok I'm good with that

**Pull request merged**
