### PR TITLE
Test Github action to validate the theme against docsbuild scripts.

### PR DESCRIPTION
**Pull request by JulienPalard**
Does an admin of the repo can check if we have something to enable for actions to run?

### CODE REVIEW

**Comment by hugovk** [comment]
I think GHA is enabled automatically, you just need to put a workflow file in `master` (e.g. by merging...).

**Comment by JulienPalard** [comment]
Oh.

It make it not easy to test it before merging it on master though...

**Comment by hugovk** [comment]
Indeed.

One option is to put a very basic noop workflow file in `master` first, and then a PR can test the proper one. (Or just merge and iterate from there.)

**Comment by JulienPalard** [comment]
> Or just merge and iterate from there

I think I'm happy with the current state of this one.

**Pull request merged**
