### PR TITLE
Fix problem with monospace rendering in Vivaldi

### LINKED ISSUE #98: Weird monospace bug
I have some strange issues with the monospace fonts in Vivaldi (Chrome):

image

(https://docs.python.org/3/library/logging.html)

Notice how the spacing is too large and numbers seem to be unicode symbols(?)

It looks fine in Firefox:
image

I can see there were some changes last year (#85, #87). If I change the CSS to:

```css
tt, code, pre {
    font-family: monospace, monospace;
    font-size: 96.5%;
}
```

this seems to fix my issue. Having just a single `monospace` causes the text size to be a bit strange.

### PR DESCRIPTION
**Pull request by ZedThree**
Fixes #98

### CODE REVIEW

**Review by ezio-melotti — COMMENTED** [review]
What browsers have you tested this with?
Do we know why the quoted `"monospace" was included and should we keep it somewhere in the list?

**Comment by hugovk** [comment]
Quoted "monospace" was added in https://github.com/python/python-docs-theme/pull/85 to workaround a Chrome bug, which was fixed in Chrome 96 (Nov 2021): https://github.com/python/pythondotorg/issues/1708#issuecomment-932596324.

By now, there's very little usage of Chrome 96 and older versions. Chrome 96% is 0.04% at https://caniuse.com/usage-table, and it's something like 1.68% for 96 and older.

(It would be good if we could hook up PR previews on Read the Docs or Netlify, that would make testing easier.)

**Comment by ZedThree** [comment]
I tested with Vivaldi 5.6.2867.62 and Firefox 109.0

**Review by hugovk — APPROVED** [review]
Tested building CPython docs locally using:

```diff
diff --git a/Doc/requirements.txt b/Doc/requirements.txt
index 134f39d6d7..c6d9c6a663 100644
--- a/Doc/requirements.txt
+++ b/Doc/requirements.txt
@@ -12,4 +12,4 @@ sphinxext-opengraph>=0.7.1
 
 # The theme used by the documentation is stored separately, so we need
 # to install that as well.
-python-docs-theme>=2022.1
+git+https://github.com/ZedThree/python-docs-theme@fix-monospace-vivaldi#egg=python-docs-theme
```

Looks fine on macOS Ventura 13.1 and Chrome 108:

image

And Safari 16.2:

image

And Firefox 109:

image

And Opera 93:

image

**Comment by hugovk** [comment]
And I've put a preview build up at https://hugovk-cpython.readthedocs.io/en/python-docs-theme-pr-104/ if anyone else wants to test it.

**Review by ezio-melotti — APPROVED** [review]

**Comment by hugovk** [comment]
Thank you!

**Pull request merged**
