### PR TITLE
Fix: searchbox is wrapping under the separation line for screen sizes

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Fixes https://github.com/python/python-docs-theme/issues/7.

Hello maintainers: folks who feel ok for reviewing the css changes?

cc @theacodes @ncoghlan @brettcannon @Mariatta (top contributors).

### CODE REVIEW

**Comment by brettcannon** [comment]
@tapaswenipathak please be careful about @ mentioning folks blindly to try and get a review. For instance, I have only contributed twice, so I'm not in a good position to review anything in this repo and I have 25 other notifications in GitHub right now and so this is unfortunately a distraction for me when I can't help.

But I will say thanks for trying and hopefully someone in a better position will be able to review your changes.

**Comment by JulienPalard** [comment]
Thanks for trying to enhance the CSS, I appreciate it, while not being able to understand it. Hope someone can review this :)

**Comment by tapaswenipathak** [comment]
@brettcannon: People tagged are the top contributors and maintainers in the org, I think, how else you can decide who can review a PR. No problem if you don't understand the changes. Thanks for taking the time for writing what you think.

**Comment by brettcannon** [comment]
@tapaswenipathak I would say it's not your problem to have to know who should review the PR. It's up to the project to decide how they want to handle assigning PR reviews and make sure there is a process in place to handle that.

**Comment by hugovk** [comment]
Thanks for the PR, this has since been fixed by the responsive theme (https://github.com/python/python-docs-theme/pull/46):

https://github.com/python/python-docs-theme/issues/7#issuecomment-1200736044

Let's close this.

**Pull request closed without merging**
