### PR TITLE
Fixes #45: Added info about updating the conf.py file to README file

### LINKED ISSUE #45: no theme named 'python-docs-theme' found (missing theme.conf?)
after installing this theme in virtual environment I've got "Theme error".
I do see "missing theme.conf" in the folder "venv/lib/python3.7/site-packages/python_docs_theme" but "make html" produces an error.
How can this error be fixed?

### PR DESCRIPTION
**Pull request by andy-maier**
See commit message.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@andy-maier

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by andy-maier** [comment]
I have now updated my existing b.p.o account to set my GitHub user, which was previously not set.
Let me know if I need to do anything else.

**Comment by JulienPalard** [comment]
As mentionned in #45, in [cpython's conf.py](https://github.com/python/cpython/blob/b7a78ca74ab539943ab11b5c4c9cfab7f5b7ff5a/Doc/conf.py#L69) we only use `html_theme`:

```
$ grep python.docs.theme ~/clones/python/cpython/Doc/conf.py 
html_theme = 'python_docs_theme'
```

no `extensions`, it would be interesting to understand why it works there and not for you before merging this.

**Comment by JulienPalard** [comment]
As 3 distinct people report that the extension is not needed, just the html_theme, I'm closing this PR. Thanks.

**Pull request closed without merging**
