### PR TITLE
Improve readability

### LINKED ISSUE #77: Theme: text justification looks bad (in narrow columns)
I'm stoked to see the huge improvements of the docs on mobile. This is really fantastic.

One thing I noticed, though, is that there are often huge gaps between words. For example (on Android):
image
Using "text-align: left" would make this look a lot better.

I would go further, and recommend to never ever use "justify" at all: it generally reduces readability and often simply looks bad. Even with wider columns it often becomes a typographic disaster (Safari, desktop):
image

### PR DESCRIPTION
**Pull request by obulat**
Fixes #77

Replace `text-align: justify` from the classic.css with `text-align: left`
Set line-height to 1.4 instead of 130% for some elements

### CODE REVIEW

**Comment by JulienPalard** [comment]
Beware I rebased your branch on top of master.

Oh and I tried fingerprinting the css as you told in the cache issue.

**Comment by JulienPalard** [comment]
(If we keep this fingerprinting method, we'll have to describe it in the README, to try to avoid forgetting to bump this version at release time...)

**Comment by JulienPalard** [comment]
Can be tested at: https://docs.python.org/3.10

**Comment by JulienPalard** [comment]
Thanks @obulat \o/

**Comment by ambv** [comment]
@JulienPalard, can we please release this on PyPI? I will be building 3.9.7 on Monday and would like text not to be justified.

**Comment by JulienPalard** [comment]
I think this is a good idea, yes.

@Mariatta @willingc ^

(As I don't have the rights)

**Comment by willingc** [comment]
@JulienPalard What's your PyPI username? I will give you rights.

**Pull request merged**
