### PR TITLE
Tiny docs ticket fixes

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Hey! Found few tiny issues in Python Docs Sphinx Theme I can help fix. Let me know if my PR helps in anyway, thank you.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept your contribution by verifying you have signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

Our records indicate we have not received your CLA. For legal reasons we need you to sign this before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for your contribution, we look forward to reviewing it!

**Comment by tapaswenipathak** [comment]
Signed the CLA.

**Comment by JulienPalard** [comment]
I don't get the tweak about the version banner, can you explain? Anyway we moved the banner on the cpython repostory, here: https://github.com/python/cpython/blob/master/Doc/tools/templates/layout.html#L4-L10
I would prefer not mixing this feature in two repositories. Also the python-docs-theme is aimed to be used by multiple projects around Python, not Python only, so I don't think speaking of the Python project is a good idea here.

**Comment by tapaswenipathak** [comment]
On Tue, Sep 3, 2019 at 2:22 PM Julien Palard <notifications@github.com> wrote:
>
> I don't get the tweak about the version banner, can you explain? Anyway we moved the banner on the cpython repostory, here: https://github.com/python/cpython/blob/master/Doc/tools/templates/layout.html#L4-L10
> I would prefer not mixing this feature in two repositories. Also the python-docs-theme is aimed to be used by multiple projects around Python, not Python only, so I don't think speaking of the Python project is a good idea here.

Hey! Mind you closing that issue out; my comment adds a little line
for behavior change, the base that implants the things for your change
is https://github.com/python/cpython/blob/master/Doc/tools/extensions/pyspecific.py#L450
and/or https://github.com/python/cpython/blob/master/Doc/tools/extensions/suspicious.py#L100,
I think; that I intentionally made open for discussion. Did you forget
adding inputs for more tiny fixes?

>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by JulienPalard** [comment]
> Mind you closing that issue out

You mean closing this PR? I think you can do if you think it should.

> my comment adds a little line for behavior change, the base that implants the things for your outdated docs behavioral change is https://github.com/python/cpython/blob/e1786b54162e2bfb01ca5aafa19d596c4af5a803/Doc/tools/extensions/suspicious.py#L99-L100 and/or https://github.com/python/cpython/blob/e226e83d36dfc7220d836fb7a249ce18e70cb4a6/Doc/tools/extensions/pyspecific.py#L449-L450,

Those are functions that should output files that should be rebuild during a sphinx build, if I understand correctly, not functions that should list old deprecated documentation files.

To activate the red banner you see here https://docs.python.org/3.4/ for example, we pass the variable from the outside, as an `html_context.outdated` given directly to sphinx-build.

> I think; that I intentionally made open as a question. That said, did you forget
adding inputs for more tiny fixes?

Sorry I don't get the meaning of your sentence :( what do you mean by "inputs for more tiny fixes"? Anyway tiny fixes are welcome, please try to put a single one per pull request.

**Comment by tapaswenipathak** [comment]
On Tue, 3 Sep 2019, 17:27 Julien Palard, <notifications@github.com> wrote:

> Mind you closing that issue out
>
> You mean closing this PR? I think you can do if you think it should.
>

If you close that single issue/feature out #24, I can close the PR linked
with that.

> my comment adds a little line for behavior change, the base that implants
> the things for your outdated docs behavioral change is
> https://github.com/python/cpython/blob/e1786b54162e2bfb01ca5aafa19d596c4af5a803/Doc/tools/extensions/suspicious.py#L99-L100
> and/or
> https://github.com/python/cpython/blob/e226e83d36dfc7220d836fb7a249ce18e70cb4a6/Doc/tools/extensions/pyspecific.py#L449-L450
> ,
>
> Those are functions that should output files that should be rebuild during
> a sphinx build, if I understand correctly, not functions that should list
> old deprecated documentation files.
>
> To activate the red banner you see here https://docs.python.org/3.4/ for
> example, we pass the variable from the outside, as an
> html_context.outdated given directly to sphinx-build.
>

Cool. Instead of doing the inside outside discussion, factually, we can
close that single issue out. Otherwise interested folks will be
unecessarily PR.

> I think; that I intentionally made open as a question. That said, did you
> forget
> adding inputs for more tiny fixes?
>
> Sorry I don't get the meaning of your sentence :( what do you mean by
> "inputs for more tiny fixes"? Anyway tiny fixes are welcome, please try to
> put a single one per pull request.
>

I fixed few issues, can be found in the PR you are commenting; per commit
there is a ticket. If you think you can review feel free letting me know
any of your inputs. Pl. let me know if you want separate PRs per each
single issue. I would obviously like closing as more and interesting
tickets as I can being a little useful in open source. Best.

**Comment by JulienPalard** [comment]
Issue #24 closed, thanks for noticing I forgot to close it :)

Sadly to review other points (CSS and viewports and so) I'm not skilled enough :-(

**Comment by tapaswenipathak** [comment]
> Issue #24 closed, thanks for noticing I forgot to close it :)
💥 

> Sadly to review other points (CSS and viewports and so) I'm not skilled enough :-(

No problem! More maintainers can review the PR in the week.

**Comment by tapaswenipathak** [comment]
Ping: maintainers.

**Pull request closed without merging**
