### PR TITLE
Correct invalid property name

### PR DESCRIPTION
**Pull request by Privat33r-dev**

### CODE REVIEW

**Review by pradyunsg — APPROVED** [review]

**Comment by hugovk** [comment]
Yes, we should fix this :)

But should we fix it by _removing_ `text-size`, and not reducing the font size? So essentially maintain the status quo? I think I prefer the bigger ">>>" button:

# Status quo: not setting `font-size`

image

https://python-docs-theme-previews.readthedocs.io/en/latest/tutorial/introduction.html#numbers

# PR: `font-size: 75%;`

image

https://python-docs-theme-previews--178.org.readthedocs.build/en/178/tutorial/introduction.html#numbers

**Comment by Privat33r-dev** [comment]
From one point, it fixes the CSS, from the other point, it makes the element a bit small
image
image

As I was writing, you posted the same thing as well. I think that removal of the `text-size` property would be more desirable and if 2 people have the same idea independently, I guess that it's a valid point.

**Review by hugovk — APPROVED** [review]
👍 

@pradyunsg What do you think?

**Review by ezio-melotti — APPROVED** [review]

**Review by pradyunsg — APPROVED** [review]

**Comment by pradyunsg** [comment]
> @pradyunsg What do you think?

Good catch, and looks like this is good to merge! :)

**Pull request merged**
