### PR TITLE
Use default pygments theme

### PR DESCRIPTION
**Pull request by Blendify**
The default theme looks a lot better than the default theme with the green background.

### CODE REVIEW

**Comment by the-knights-who-say-ni** [comment]
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).

## Recognized GitHub username

We couldn't find a [bugs.python.org](https://bugs.python.org/) (b.p.o) account corresponding to the following GitHub usernames:

@Blendify

This might be simply due to a missing "GitHub Name" entry in one's b.p.o account settings. This is necessary for legal reasons before we can look at this contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.




You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

**Comment by JulienPalard** [comment]
Before : 
Screenshot_2021-03-23 http client — HTTP protocol client — Python 3 9 2 documentation(1)
After :
Screenshot_2021-03-23 http client — HTTP protocol client — Python 3 9 2 documentation

**Comment by pradyunsg** [comment]
Is anything blocking this merging?

**Comment by JulienPalard** [comment]
I think it's subjective, I fear someone will open a PR to use Sphinx instead of defaut telling it looks better and we enter an infinite loop.

So what's blocking this PR is the lack of concensus. Maybe open an poll on discuss.python.org or twitter, and if the concensus is clear, we could merge this.

- I see one good point: redish literals do pop out cleaner.
- I see one bad point: light grey output is less readable.

**Comment by pablogsal** [comment]
I can apport a non-subjective point: I am very colorblind and I can read much better the second one

**Comment by JulienPalard** [comment]
> I can apport a non-subjective point: I am very colorblind and I can read much better the second one

Thanks for your feedback!

**Pull request merged**
